### ISSUE TITLE
Provide Vue3 Support

### ISSUE THREAD

**Issue by ajmas** [mycurelabs/vue-html-to-paper#104]
Would it be possible to add Vue3 support to this project. I do appreciate this would probably need to be done as part of a major version change and possibly maintaining both a Vue2 and a Vue3 release branch.

BTW this was a useful page for when I migrated another Vue2 based project to Vue3:  https://alvarosaburido.dev/blog/how-to-migrate-your-library-from-vue2-to-vue3

**Comment by ajmas** [comment]
Just saw there was this PR, but it appears to be in Limbo: https://github.com/mycurelabs/vue-html-to-paper/pull/73

**Comment by ajmas** [comment]
I think this project is maintenance limbo. Source hasn’t been updated in 7 months. Probably best to make a Vue3 specific fork?

**Comment by markhermano** [comment]
I rewrote the plugin to provide support for Vue 3 options and composition API.
[Paperizer](https://github.com/markhermano/paperizer)

**Comment by jofftiquez** [comment]
@ajmas please check `v2.0.x` for the vue 3 support!

**Comment by jofftiquez** [comment]
> I rewrote the plugin to provide support for Vue 3 options and composition API. [Paperizer](https://github.com/markhermano/paperizer)

Cool project @markhermano, thanks for sharing <3

**Comment by markhermano** [comment]
@jofftiquez I thought about rewriting whilst waiting for Vue 3 support on this project :smiley:  . Thanks for the new update on this project.

**Comment by jofftiquez** [comment]
> @jofftiquez I thought about rewriting whilst waiting for Vue 3 support on this project 😃 . Thanks for the new update on this project.

You should showcase your project in [OSSPH](https://ossph.org)'s discord 😊

**Comment by ajmas** [comment]
Good to know. I’ll check out the work when I have a few moments.
