### ISSUE TITLE
access $htmlToPaper function in script setup

### ISSUE THREAD

**Issue by cobategit** [mycurelabs/vue-html-to-paper#118]
i find how to access $htmlToPaper in script setup,

first me declare in app.js 
`app.provide("nameProvide", app.config.globalProperties.$htmlToPaper);`

and in your file want to generate pdf
`import { inject } from "vue";`
`const globalProvide = inject("nameProvide");`

**Comment by jaywilburn** [comment]
How are you using it after you inject it?
