### ISSUE TITLE
Demo gives a 404

### ISSUE THREAD

**Issue by hay** [mycurelabs/vue-html-to-paper#16]
Hey,
it seems the demo link in the README points to a 404:

https://mycure-inc.github.io/vue-html-to-paper/

Maybe it's changed to something else?

**Comment by jofftiquez** [comment]
New demo link is https://mycurelabs.github.io/vue-html-to-paper/

We've recently changed our organization name. Sorry about that.

**Comment by hay** [comment]
Thanks!
