### ISSUE TITLE
vue-html-to-paper is difficult to initialize, no sensible defaults, no descriptive error messages

### ISSUE THREAD

**Issue by NathanStrutz** [mycurelabs/vue-html-to-paper#17]
While the component does work when it's configured properly, the configuration is a somewhat difficult and annoying process.

- options should be optional
  - default name to `_ blank`
  - default specs to `'fullscreen=yes','titlebar=yes', 'scrollbars=yes'`
  - default styles to `[]`

The callback function (`cb()`) should also be optional, and should only be called if it was passed in. Optionally, it can be defaulted to something like `()=>true;`.

**Comment by jofftiquez** [comment]
@NathanStrutz You're right. This might not be in my priority right now but I will definitely do this sooner or later. If you really need the features right now, you can do a PR. Thanks.
