### ISSUE TITLE
How to call $htmlToPaper in js file ?

### ISSUE THREAD

**Issue by brwa-ata** [mycurelabs/vue-html-to-paper#22]
Hello, guys
You did a great job and this is what I was looking for, everything works well.
But I have a question in my project there are many components I should add print to it, so I created a JS file and wrote my code there in this way any where I want to print just call that function and it should do it.
_The problem is_ when I write `this.$htmlToPaper` inside the function in JS file it gives me an error 
`Error in v-on handler: "TypeError: Cannot read property '$htmlToPaper' of undefined"`.
Please how can I call that _$htmlToPaper_ in JS file?

**Comment by nsznsznjsz** [comment]
You can't use `this.$htmlToPaper` in JS file, because ES6 module prevent `this` pointer to global, 
and $htmlToPaper mount on Vue Instance. but I also like use like `import { htmlToPaper } from 'vue-html-to-paper'`, it's more like Vue3

**Comment by brwa-ata** [comment]
ok, thanks
