### ISSUE TITLE
Lost CSS when printing

### ISSUE THREAD

**Issue by DisVoider** [mycurelabs/vue-html-to-paper#23]
I'm using Vue framework to build my project.

Now I'm faceing how to print the web page partialy,

Very Thanks to this plugin for convinence

BUT! I can't find out how to use my '.css' file to print the right page correctly

the project structure like below
--project
   |--src
        |--main.js
        |--mycss.css
        |--(other folder)
        |--views (folder)
              |--record (folder)
                     |--css (folder)
                     |      |--mycss.css
                     |--pageToPrint.vue (I need to print part of it)

I use 'options' in my 'main.js' , and set it in my 'main. js'
And I use 'this.$htmlToPaper( idToPrint )' in pageToPrint.vue
as same as README said

I've tried relative path and put it into ' styles ', but it not worked
      like  'src/views/records/css/mycss.css',
             '../css/mycss.css'  and SO ON

**Comment by eigarrido** [comment]
I have the same problem

**Comment by SivamaliniV** [comment]
Give a try with inline CSS. Its works for me.

**Comment by KhalifaGad** [comment]
Try using absolute path to your css file, it works for me.

**Comment by imanever8** [comment]
I have the same problem
I solved with external css file

**Comment by davidrock** [comment]
You also can solve that putting your css files into the /public folder and referencing the folder.
For me, I put the necessary css files for print in the root  of the /public folder, and passed the options this way:

```
const localOptions = {
   styles: [
          'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css',
          './docs.css',
          './landscape.css'
        ]
};

this.$htmlToPaper('doc', localOptions });
```

That was the only way I could make it works

**Comment by jofftiquez** [comment]
Exactly, use the public folder because that's the root directory for assets likes this.

**Comment by jofftiquez** [comment]
Closing this for now. Kindly re-open if you have more issues or open a new issue. Thanks.
