### ISSUE TITLE
Cannot print image

### ISSUE THREAD

**Issue by brwa-ata** [mycurelabs/vue-html-to-paper#24]
I want to print an invoice which contain a logo of the company I putted the logo in the header but on print the image will not appear even I checked **background graphics** in print option, any idea about it?

**Comment by yohanesisa** [comment]
@brwa-ata hii, i'm currently facing similar issue... May i know how you handle it? thanks

**Comment by jofftiquez** [comment]
Any styles that you want to persist in the print page. Add inside the `@media print` block, like so:

```
@media print {
  // custom styles only for print page
}
```
