### ISSUE TITLE
How to change save pdf name dynamically?

### ISSUE THREAD

**Issue by SivamaliniV** [mycurelabs/vue-html-to-paper#25]
Hi, Thanks for this plugin. It saves my day. But, While saving the pdf its automatically taken the header name as pdf name. Instead of this can I have my own dynamic name?

const options = {
  name: '_blank',
  specs: [
    'fullscreen=yes',
    'titlebar=yes',
    'scrollbars=yes'
  ],
  styles: [
    'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css',
    'https://unpkg.com/kidlat-css/css/kidlat.css'
  ]
}

I have tried with name option. but it won't work.

**Comment by jofftiquez** [comment]
Hello will add this functionality in #36
