### ISSUE TITLE
Loading CSS for different components.

### ISSUE THREAD

**Issue by june4th** [mycurelabs/vue-html-to-paper#26]
Hi, I have a problem when trying to load different CSS for the different components in my project. When I load local CSS in component A 

`const options = {
        name: '_blank',
        specs: [
            'fullscreen=yes',
            'titlebar=yes',
            'scrollbars=yes'
        ],
        styles: [
            'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css',
            'https://unpkg.com/kidlat-css/css/kidlat.css',
            '/css/printWeeklyReport.css'
        ]
    }`
It worked well.

But next, when I loading the CSS in component B with different content it was not applied it still loading the first CSS in component A.

`const options = {
        name: '_blank',
        specs: [
            'fullscreen=yes',
            'titlebar=yes',
            'scrollbars=yes'
        ],
        styles: [
            'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css',
            'https://unpkg.com/kidlat-css/css/kidlat.css',
            '/css/print.css'
        ]
    }`
If I refresh and load component B first so the CSS of B still applying although open the component A after that.

How I can fix it? CSS of B only applies for B and CSS of A only applies for A?

**Comment by jofftiquez** [comment]
Hello @june4th I understand. Since the option for adding styles is set to global, there's no way to add a different style for a different component. This will be fixed in #36 thank you.
