### ISSUE TITLE
Return a promise when miss callback

### ISSUE THREAD

**Issue by nsznsznjsz** [mycurelabs/vue-html-to-paper#27]
Hey! Thanks for your plugins, it makes me save a lot of time.

Sometime callback is useful, but I prefer to use async/await instead of callback, can we return a promise when miss callback?

```
const promise = new Promise()

setTimeOut(() => {
  // ...
  if (cb) cb()
  promise.resolve(true)
} , 1000)

return cb? ture: promise
```

**Comment by jofftiquez** [comment]
Hello @nsznsznjsz you're right. I can consider this, however I can't promise to do this very soon. If you can do a PR it would be much appreciated.
