### ISSUE TITLE
Please note faq for landscape print layout

### ISSUE THREAD

**Issue by songwutk** [mycurelabs/vue-html-to-paper#35]
I'd like to print A4 landscape instead A4 portrait, but no instruction.

**Comment by jofftiquez** [comment]
Hello @songwutk, you can change the layout from portrait to landscape in the browser's print page.

**Comment by jofftiquez** [comment]
Will update the docs for automatic landscaping, I believe it's available in the print api.

**Comment by songwutk** [comment]
> Hello @songwutk, you can change the layout from portrait to landscape in the browser's print page.

I'm tried in my chrome for  windows click menu item but dialog not show.
Chrome for ubuntu dialog show ,select landscape  but real pdf output still portrait, firefox, too.

This quite serious function.

**Comment by jofftiquez** [comment]
Thanks for the feedback @songwutk songwutk

**Comment by jofftiquez** [comment]
Actually @songwutk you can achieve this by passing a custom css in the styles options. Create a `landscape.css` and add this. 

```
@media print {
  @page {
    size: landscape
  }
}
```
Then, inject the css to styles options like so:

```
styles: [
        'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css',
        'https://unpkg.com/kidlat-css/css/kidlat.css',
        ./path/to/landscape.css'
      ]
```

**Comment by jofftiquez** [comment]
#36
