### ISSUE TITLE
Local Options doesn't override the Global options

### ISSUE THREAD

**Issue by Andrades-r** [mycurelabs/vue-html-to-paper#37]
I am using an global options and in main.js is like:

```
const optionsHtmlToPaper = {
  name: "_blank",
  specs: ["fullscreen=yes", "titlebar=yes", "scrollbars=no", "size=landscape"],
  styles: [
    "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css",
    "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
  ]
};

Vue.use(VueHtmlToPaper, optionsHtmlToPaper);
```
It doesn't import the icons from font-awesome library and i am trying to put landscape in one page specific, on the component my code is like
```
print() {
      const test = {
        styles: [
          "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css",
          "./landscape.css",
        ]
      };
      this.$htmlToPaper("guias-impressao",test, () => console.log("printed"));
    }
```

It doesn't override the global options and i got this error message: "Uncaught TypeError: n is not a function at eval"

**Comment by jofftiquez** [comment]
I'm pretty sure I tested this one. Can you check the demo page? Let me check also. For the meantime could create a reproduction link? Thanks.

**Comment by jofftiquez** [comment]
Can you answer these? 

1. What version are you using?
2. Are you sure the css is in the right place?

**Comment by Andrades-r** [comment]
I made a sandbox in this link: https://codesandbox.io/s/misty-sun-n8e5j
the path of the css file should be the path from the main to the css or from the file where i  defined the local options? I am using the last one

**Comment by jofftiquez** [comment]
Thank you! Will check the sandbox. The path of the css should be relative to the component where you called it.

**Comment by jofftiquez** [comment]
I think I understand the problem now. Since we are using relative path, the server is looking for the css in the public folder. If you are using vue-cli-3 project, just put your css in the public folder. Then import it like `./landscape.css`

**Comment by jofftiquez** [comment]
Please see this fork of you reproduction https://codesandbox.io/s/cold-cookies-qtfs0
