### ISSUE TITLE
cannot read property 'document' of null

### ISSUE THREAD

**Issue by chaule97** [mycurelabs/vue-html-to-paper#40]
When I run code print, I have a error:
`Uncaught TypeError: Cannot read property 'document' of null`

This is my code:
`this.$htmlToPaper('print', null, () => {
          this.printed = true
        })`

Can you explain? Thank you so much

**Comment by jofftiquez** [comment]
Hi @chaule97 let me look. Thanks.

**Comment by jofftiquez** [comment]
Can you tell me which line is the error coming from? @chaule97
