### ISSUE TITLE
How to cancel the preview window？

### ISSUE THREAD

**Issue by liuquanzhang** [mycurelabs/vue-html-to-paper#41]
How to print directly on the original page without preview

**Comment by jofftiquez** [comment]
Hello @liuquanzhang you cannot achieve that using this plugin. You'll notice [here](https://github.com/mycurelabs/vue-html-to-paper/blob/2f7278d94aefdc947e6c23a3deb831fe9f26bf13/src/index.js#L44) that it is opening a new window. Thanks.
