### ISSUE TITLE
How to show some elements that are hidden on html?

### ISSUE THREAD

**Issue by AleksandarMiha** [mycurelabs/vue-html-to-paper#42]
Hello i want to show any element which is hidden in html. 
Example

```
<div id="printMe">
<h1> Show show </h1>
<p> I WANT THIS P TAG TO HIDE FROM HTML BUT SHOW IN VUE PAPER </p>
</div>
```

Thanks.

**Comment by AleksandarMiha** [comment]
@warlock jofftiquez

**Comment by AleksandarMiha** [comment]
@jofftiquez

**Comment by AleksandarMiha** [comment]
@igemnace

**Comment by jofftiquez** [comment]
Use `v-if` set the default value to false. Then make it true when the print method is called.

**Comment by AleksandarMiha** [comment]
@jofftiquez  
it is no work
Check my question
https://stackoverflow.com/questions/61126059/how-to-hide-element-in-vue-html-to-paper/61126377?noredirect=1#comment108142285_61126377

**Comment by AleksandarMiha** [comment]
@jofftiquez @igemnace @warlock @enometsys @

**Comment by jofftiquez** [comment]
Hello @AleksandarMiha we appreciate you for using our plugin, however, the problem you're encountering is not part of the solution that this plugin is offering. Can you maybe create a reproduction via codepen or jsfiddle? Thanks.

**Comment by jofftiquez** [comment]
@AleksandarMiha do this:

```javascript
print () {
  this.showInPrint = true; // show the <p> tag

  // Use nextTick to trigger the print on next update
  this.$nextTick(() => {
    vm.$htmlToPaper('printMe', null, () => {
      console.warn('done');
    });
  });
},
```

**Comment by AleksandarMiha** [comment]
Yes friend. 
Solution is this.$nextTick. 
Thanks :)

**Comment by AleksandarMiha** [comment]
Hmm but i have another problem.
When i goes to print function. If go to cancel  I lose my element in html. 
I need go to refresh page to see again p tag.
Solution?

**Comment by AleksandarMiha** [comment]
@jofftiquez @warlock @enometsys @igemnace
