### ISSUE TITLE
How to print vue-chartjs?

### ISSUE THREAD

**Issue by bluesky93128** [mycurelabs/vue-html-to-paper#44]
I have some charts on my page and want to print it.
How can I do it?

**Comment by jofftiquez** [comment]
Hello @bluesky93128 can you show me what you have tried so far?

**Comment by bluesky93128** [comment]
I've converted the chart as image by using getDataUrl() function.
and show it in an img tag.
Is there any way to print vue-chart directly?

**Comment by jofftiquez** [comment]
I am not sure if that's achievable, to directly print the chart from `vue-chart`. But what your're currently doing is fine. Just print the image. That way you don't have to load the `vue-chart` in the print window.

**Comment by jofftiquez** [comment]
Is there any updates on this? Closing for now.
