### ISSUE TITLE
Cannot set local or global options

### ISSUE THREAD

**Issue by luisluft** [mycurelabs/vue-html-to-paper#46]
I have tried everything, adding local options, global options, inline css, absolute path, relative path, but haven't been able to apply custom options.  I am using vuetify and 
This is the folder structure:
![image](https://user-images.githubusercontent.com/53981590/82733933-668a3980-9ce5-11ea-9444-fe5804e037f2.png)
This is the code for CCI.vue:
```
<template>
  <v-container id="print_me">
    <v-card class="px-5" outlined>
    </v-card>
  </v-container>
</template>

<script>
const local_options = {
  styles: ["../../assets/print.css"]
};
export default {
  methods: {
    print() {
      this.$htmlToPaper("print_me", local_options);
    },
  },
};
</script>

```
This is the code for print.css:
```
@media print {
  @page {
    size: landscape;
  }
}
```
I also keep getting this warning in my chrome developer console:
![image](https://user-images.githubusercontent.com/53981590/82742123-ea651580-9d27-11ea-8959-f8c7d4679065.png)

**Comment by jofftiquez** [comment]
Hello you should put the custom css in the `public` directory.

**Comment by luisluft** [comment]
I moved the css into the public directory but the same behaviour continues.
