### ISSUE TITLE
how can used without windows.open?????

### ISSUE THREAD

**Issue by Omarillo** [mycurelabs/vue-html-to-paper#48]

**Comment by jofftiquez** [comment]
Hello @Omarillo you can't at the moment. But this can be a nice feature, to let the user choose whether to show in on the same page or show it in a new tab. Let me know your thoughts.

**Comment by Omarillo** [comment]
is there a way to do changing the code for my self

**Comment by jofftiquez** [comment]
Yes, you can do a pull request to this repository. Just add a new option called `openInNewWindow` and use that to do a conditional statement on this line https://github.com/mycurelabs/vue-html-to-paper/blob/2f7278d94aefdc947e6c23a3deb831fe9f26bf13/src/index.js#L44.

**Comment by jofftiquez** [comment]
@Omarillo actually, my bad. You just gotta set the name option as `_self`. Like so:

```
{
  "name": "_self",
  //  ...other options
}
```

**Comment by jofftiquez** [comment]
Any updates? Will close this now. Thanks.
