### ISSUE TITLE
reporting documentation bug

### ISSUE THREAD

**Issue by FaruqueBraimo** [mycurelabs/vue-html-to-paper#50]
Hello, I am openning this issue to report a little bug that i found in the [documentation  ](https://randomcodetips.com/vue-html-to-paper/).
so  the component created in the documentation:

`<tamplate>
//code
 <button @ click = "print"> </button>
<tamplate>
`
it missing to close a tag and place a text on the button, because in many cases this button is not rendered when it has no text. so here is the small soluction :
`<tamplate>
//code
 <button @ click = "print"> print</button>
</tamplate>
`

Thanks for making the lib ❤️

**Comment by jofftiquez** [comment]
Wow, I missed that. Thank you so much @FaruqueBraimo much appreciated.

**Comment by paulocuambe** [comment]
This should be closed by now 😅
