### ISSUE TITLE
Unable to print using samsung phones

### ISSUE THREAD

**Issue by Tommvv** [mycurelabs/vue-html-to-paper#52]
After creating a scan application with the use of phones, I stumbled upon a problem that I have tried debugging.

I have tested using Samsung phones (S10, S20 & X Cover) aswell as iPhone (10 & 11).
I came to the conclusion that its not possible to print pages using vue-html-to-paper on samsung, it is however possible on iPhone.

I have tested this using your demo aswell as our production application.
I do not want to say bye to vue-html-to-paper as it serves us well on desktop.

I am not quite sure how to go about this as the demo doesn't work either.
Id love some input.

<div style="display=inline-block">
<img src="https://user-images.githubusercontent.com/32355829/87550855-cf6fab80-c6af-11ea-8fcc-2af5273876f6.jpg" width="25%" height="25%">
<img src="https://user-images.githubusercontent.com/32355829/87550861-d1396f00-c6af-11ea-9e0f-c153a195407b.jpg" width="25%" height="25%">
</div>

**Comment by jofftiquez** [comment]
Hi, refer to #78. Still debugging this one. Thanks.

**Comment by JonatasBSM** [comment]
I'm still having the same problem. I discovered that the problem appears when using autoClose = true. My guess is that print page closes before start printing
