### ISSUE TITLE
css does not work when internet connection is slow

### ISSUE THREAD

**Issue by nnnayeem** [mycurelabs/vue-html-to-paper#54]
Hello,

I am trying to pring using vue-html-to-paper. On my local server everything works fine. When I upload to live server the css seems to does  not work even though the css link is correct (I can see the loaded css link using chrome dev tool).

So I tried to find out the root cause. In the option I changed `name:'_blank'` to `name:'_self` and and make the internet to 2G using chrome dev tool and I successfully has recreate the problem in local server. It seems browser start printing event before loading the css. In my config file:

```
const options = {
     name: '_self',
     specs: [
          'fullscreen=yes',
          'titlebar=yes',
          'scrollbars=yes'
     ],
     styles: [
          "/css/style.css",
     ]
}
```
and priting using `this.$htmlToPaper('printInvoice')` .

Is there any mistake that I am doing. I would really happy if you could point my mistake or any workaround.

Thanks in advance

**Comment by mohdabbas** [comment]
I am facing the same issue :-(...

**Comment by varna9000** [comment]
Same problem here.

**Comment by mohdabbas** [comment]
Yes, fixed by increasing the setTimeout Value!

**Comment by varna9000** [comment]
@mohdabbas yes, but it's more of a workaround. It's best if the print() function could wait for the css to load in full, I suppose.

**Comment by dmcbrn** [comment]
Can someone please review this, accept PR if all good, and create new revision?

**Comment by jofftiquez** [comment]
Hello @dmcbrn I apologize, the team has been very busy with work lately. I will check your PR. Thank you for your help.

**Comment by jofftiquez** [comment]
Hi I recently deployed `v1.4.1` thanks.
