### ISSUE TITLE
how to set the default margin to none

### ISSUE THREAD

**Issue by hqzh** [mycurelabs/vue-html-to-paper#55]
![1](https://user-images.githubusercontent.com/26128706/88453264-fa1fe800-ce97-11ea-9343-e200a81ef053.png)

**Comment by jakedolan** [comment]
Browser support may vary depending on its implementation of @page (https://caniuse.com/#feat=mdn-css_at-rules_page), but you should be able to control both the display achieve this with the following in a print style for both the print window and print output.

```
@media print {
    @page {
        margin: 0;
    }
}
@media screen {
    body {
       margin: 0;
    }
}
```

**Comment by jofftiquez** [comment]
Hello, are you still facing this issue? Thanks.

**Comment by hqzh** [comment]
> Hello, are you still facing this issue? Thanks.

it's still

**Comment by hqzh** [comment]
https://www.matuzo.at/blog/i-totally-forgot-about-print-style-sheets/
