### ISSUE TITLE
Should this console.warn be here?

### ISSUE THREAD

**Issue by joshmakar** [mycurelabs/vue-html-to-paper#57]
I get a console warning anytime I print and it's just an empty array since I'm not passing any style options.

Not a big deal but just adds noise to the console log and may cause future devs of our app to want to try and troubleshoot the warning if they don't know what it is already.

Great job on the package btw and thanks for creating it!

https://github.com/mycurelabs/vue-html-to-paper/blob/05e5e10450f81d990cd8be273a8b1534d6ce959d/build/vue-html-to-paper.js#L40

**Comment by jofftiquez** [comment]
Hello @joshmakar you're right. This is a mistake. Would you mind making a PR for this? Thanks.

**Comment by joshmakar** [comment]
Didn't see your response until after you'd finished the PR. Thanks!
