### ISSUE TITLE
Help with Print settings

### ISSUE THREAD

**Issue by Zanndorin** [mycurelabs/vue-html-to-paper#61]
Hi, I don't think I'm using this correctly.

I am trying to make the print label sized

```
@media print {
    @page {
        size: 50mm 25mm;
        margin: 2mm;
    }
}
```
I added this to a print.css file.

and I call it 

```
printLabel() {
      const localOptions = {
        name: '_blank',
        styles: [
          'print.css' // Have tried with ./print and /print
        ]
      };
      this.$htmlToPaper('printMe', localOptions, () => {
        console.warn('done landscape');
      });
    },
```

but I think the size thingie are ignored? or is this related to https://github.com/mycurelabs/vue-html-to-paper/issues/47

**Comment by jofftiquez** [comment]
Hello @Zanndorin I am currently still investigating this on my end. One possible reason might be the permission to the `public` folder. Altho I am not yet certain about it. Would you mind using the a CDN at the moment? Thanks.

**Comment by jofftiquez** [comment]
Duplicate #47
