### ISSUE TITLE
How can we not to show the preview window ?, just need to show the print window

### ISSUE THREAD

**Issue by tamanna-makkar** [mycurelabs/vue-html-to-paper#64]

**Comment by jofftiquez** [comment]
In the install options, or in the local options upon the invocation of the method `this.$htmlToPaper` there's actually a property called `name`. It is by default set to `_blank` so it opens a new tab or a new window. To make it load to the same page you can pass the value `_self` to the `name` property, like so:

```javascript
{
  name: '_self',
  styles: [...]
}
```
