### ISSUE TITLE
How to change filename of the pdf donwload

### ISSUE THREAD

**Issue by SamZuckerberg** [mycurelabs/vue-html-to-paper#70]
When the user try to download the pdf, the name comes empty.

How can I set a name for the download?

Thanks!

**Comment by mehawk5** [comment]
Hi, this is a temporary solution, it's kind of silly but it works.
htmlToPaper is programed to tike the page title as a name for the document to be printed, so changing the title then switching it back works.
print() {
    const title = document.title;
    document.title = this.selectedSubvention.subventionHolderName ?? "";
    this.$htmlToPaper("printMe", this.options);
    document.title = title;
  }

**Comment by jofftiquez** [comment]
Hi please see `v1.4.1` I added a new option for overriding the window title.
