### ISSUE TITLE
using vuetify cdn?

### ISSUE THREAD

**Issue by khyvez** [mycurelabs/vue-html-to-paper#80]
How can I use this using vuetify?

**Comment by jofftiquez** [comment]
Hello @khyvez just import the plugin like a normal vue plugin. Instructions are in the documentations.

If you are worried about the css conflict, you can actually pass a custom css in the plugin to override the css of your framework.

**Comment by khyvez** [comment]
I mean how can I use the vuetify style?

**Comment by jofftiquez** [comment]
@khyvez same concept would apply you can use vuetify css.
