### ISSUE TITLE
Custom style print not work with vue please help?

### ISSUE THREAD

**Issue by phanchanra** [mycurelabs/vue-html-to-paper#81]
Hello, I have using html to paper in vue with custom style, but not working

     `const options = {
            name: '_blank',
            specs: [ 'fullscreen=yes',   'titlebar=yes',  'scrollbars=yes' ],
            styles: [ './client/styles/style.css']
       }
      Vue.use(VueHtmlToPaper, options);`
I put my style in correct path, but when I click print button style not working
Please help

**Comment by jofftiquez** [comment]
Please put the custom style in the public directory, together with your favicon. Thanks.

**Comment by phanchanra** [comment]
I put in public also but it still not work Please any code test online

**Comment by jofftiquez** [comment]
Would you mind sharing how you implemented it? A reproduction link would be great. Thanks.

**Comment by phanchanra** [comment]
I want to ask you, Do you have any suggestion?

**Comment by jofftiquez** [comment]
Send me a reproduction link, that's my suggestion. So I can look at it.

**Comment by phanchanra** [comment]
Please check https://randomcodetips.com/vue-html-to-paper/ with inject the custom css in the styles option

**Comment by jofftiquez** [comment]
Send me a reproduction link, that's my suggestion. So I can look at it.

**Comment by phanchanra** [comment]
I'm just asking you, do you have any procedure to extract style from folder other than public?

**Comment by jofftiquez** [comment]
> I'm just asking you, do you have any procedure to extract style from folder other than public?

No there are none. If such thing exists it would be in the documentation. Do you still want me to help you, if so send a reproduction link.
