### ISSUE TITLE
How to hidden content in popup?

### ISSUE THREAD

**Issue by haitd-qest** [mycurelabs/vue-html-to-paper#82]
I want hidden conttent in image
https://uphinh.org/image/ycRnoE
Pls help me.

**Comment by jofftiquez** [comment]
Hi please provide more description. I will close this for now. Thanks.

**Comment by haitd-qest** [comment]
I want to hide html content in popup or set the popup width equal to printed text. Because it doesn't look good.
https://uphinh.org/image/y7PgEP

> Hi please provide more description. I will close this for now. Thanks.

**Comment by jofftiquez** [comment]
@haitd-qest I understand, there's no way to do that really. This behavior is just like as when you press `Ctrl + P`.
