### ISSUE TITLE
On cancel or close the main window opened where a print button is embedded closes too! how do i only close the print and preview and not my main tab?

### ISSUE THREAD

**Issue by jovi09** [mycurelabs/vue-html-to-paper#97]

**Comment by MixinsSmartSystem** [comment]
@ open the index.js for VueHtmlToPaper by click on .
after the line 76 add this line
win.close()

**Comment by syx-pravin** [comment]
To stay on your main tab and to close only print dialogue, you need to do the following changes.

open index.js and search for the line 

**setTimeout(function () {window.close();}, 1);
          cb();
}, 1000);**

and **replace** this code with

**setTimeout(function () {}, 1);
          cb();
}, 1000);**

Now add **win.close();** after **win.print();** statement.

**Comment by rayamjad** [comment]
Just replace 
setTimeout(function () {window.close();}, 1);
cb();
}, 1000);

with

setTimeout(function () {win.close();}, 1);
cb();
}, 1000);
